version: "3.7"

services:

  flask:
    build: ./backend
    image: flask
    container_name: flask-app
    restart: always
    ports:
      - "5000:5000"
    expose:
      - 5000

  http-server:
    build: ./frontend/activity-heatmap
    container_name: vue-app
    restart: always
    ports:
      - "8080:8080"